version: '3'
services:
  airflow:
    image: apache/airflow:latest
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - AIRFLOW__CORE__FERNET_KEY=myFernetKey
      # Outras variáveis de ambiente do Airflow
    ports:
      - "8080:8080"
    networks:
      - airflow-network
    # Outras configurações necessárias

networks:
  airflow-network:
